# Railway Internal MongoDB (Stable, Never Changes)
spring.data.mongodb.uri=${MONGO_PUBLIC_URL}

# Database Name
spring.data.mongodb.database=chatapp

# Frontend URL
frontend.base.url=https://chathiveapp.netlify.app