# MongoDB Atlas Connection
spring.data.mongodb.uri=${MONGO_URL}

# Database Name (Must match Atlas)
spring.data.mongodb.database=chatapp

# Frontend URL
frontend.base.url=https://chathiveapp.netlify.app