# MongoDB Configuration
spring.data.mongodb.uri=${MONGO_PUBLIC_URL}
spring.data.mongodb.database=chatapp

# Server Configuration
server.port=8080

# Frontend URL (CORS ke liye)
frontend.base.url=${FRONT_END_BASE_URL}

# Logging
logging.level.root=INFO
logging.level.com.substring.chat=INFO